services:
  backend:
    build: ./app/backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  frontend:
    build: ./app/frontend
    ports:
      - "8501:8501"
    command: streamlit run main.py --server.port=8501

  lancedb:
    image: cledge/lancedb:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
