version: '3.8'
services:
  backend:
    build: ./app/backend
    ports:
      - "8000:8000"
  frontend:
    build: ./app/frontend
    ports:
      - "8501:8501"
  lancedb:
    image: lancedb/lancedb:latest
    ports:
      - "8080:8080"
